metadata_dir = "/meta"
data_dir = "/data"

replication_factor = 1
consistency_mode = "consistent"
db_engine = "sqlite"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "${GARAGE_RPC_SECRET}"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage"

[s3_web]
bind_addr = "[::]:3903"
root_domain = ".web.garage"
index = "index.html"

[admin]
api_bind_addr = "[::]:3902"
